#!/usr/bin/env python

import sys

from arm_marmotte_rqt.my_module import MyPlugin
from rqt_gui.main import Main

plugin = 'arm_marmotte_rqt'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
